- name: Install podman and tools
  package:
    name:
      - fuse-overlayfs
      - slirp4netns
      - buildah
      - podman
      - checkpolicy
      - setools-console
    state: latest

- name: create user podboy
  user:
    name: podboy
    expires: -1
    seuser: user_u
    password_lock: yes
    password: "!"

- name: create appli folder
  file:
    path: /appli
    owner: podboy
    group: podboy
    mode: 'u=rwx,g=rx,o=rx'
    state: directory