- name: Install podman and tools
  package:
    name:
      - fuse-overlayfs
      - slirp4netns
      - buildah
      - podman
      - checkpolicy
      - setools-console
    state: latest

- name: copy config files
  template:
    src: "{{item}}.j2"
    dest: "/etc/containers/{{item}}"
  with_items:
    - containers.conf
    - storage.conf

- name: create user podboy
  user:
    name: podboy
    expires: -1
    # seuser: user_u
    password_lock: yes
    password: "!"

- name: create appli folder
  file:
    path: /appli
    owner: podboy
    group: podboy
    mode: 'u=rwx,g=rx,o=rx'
    state: directory

- name: Enable linger for podboy user
  command: "loginctl enable-linger podboy"