- name: install watchtower
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    restart_policy: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
    command:
      [
        "--cleanup",
        "--include-restarting",
        "--schedule",
        "0 0 4 * * *",
        "--rolling-restart",
        "--stop-timeout",
        "10m",
        "--notification-url",
        "{{ url_discord }}",
      ]
  when: url_discord is defined
