apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-gitea
  namespace: gitea
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`gitea.k3s.samoth.eu`)
    kind: Rule
    services:
    - name: gitea-http
      port: 3000