- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: false

- name: load custom modules
  copy:
    src: modules.conf
    dest: /etc/modules-load.d/modules.conf
    owner: root
    group: root
    mode: '0644'

- name: copy custom resolv file
  copy:
    src: resolv-custom.conf
    dest: /etc/resolv-custom.conf
    owner: root
    group: root
    mode: '0444'