apiVersion: v1
kind: Pod
metadata:
  name: debian
  namespace: default
spec:
  containers:
  - name: debian
    image: debian
    args:
    - sleep
    - "1000000"
    resources:
      requests:
        cpu: 20m
        memory: 20Mi
      limits:
        cpu: "1"
        memory: 1Gi