apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-gitlab
  namespace: gitlab
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`gitlab.k3s.samoth.eu`)
    kind: Rule
    services:
    - name: gitea-nginx-ingress-controller
      port: 443