postgresql:
  install: false
gitlab-runner:
  install: false
prometheus:
  install: false
certmanager:
  install: false
nginx-ingress:
  enabled: false
minio:
  install: false

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 900M
  workhorse:
    resources:
      limits:
        memory: 100M
      requests:
        cpu: 10m
        memory: 10M
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    resources:
      limits:
        memory: 1.5G
      requests:
        cpu: 50m
        memory: 625M
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
  gitaly:
    resources:
      requests:
          cpu: 50m
          memory: 64Mi
    persistence:
      size: 25Gi
  shared-secrets:
    resources:
        requests:
          cpu: 10m
          memory: 64Mi
  migrations:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
  toolbox:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
    backups:
      objectStorage:
        config:
          secret: gitlab-backup-storage
          key: config

global:
  edition: ce
  hosts:
    domain: k3s.samoth.eu
    https: true
    kas:
      name: gitlab-kas.k3s.samoth.eu
  ingress:
    configureCertmanager: false
    enabled: true
    provider: traefik
    class: traefik
    tls:
      enabled: false
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
  gitlab-shell:
    traefik:
      entrypoint: "gitlab-shell"
  psql:
    host: gitlab-database.gitlab
    port: 5432
    database: gitlab
    username: gitlab
    password:
      useSecret: true
      secret: gitlab.gitlab-database.credentials.postgresql.acid.zalan.do
      key: password
  minio:
    enabled: false
  registry:
    bucket: gitlab-registry
  appConfig:
    lfs:
      enabled: false
    artifacts:
      bucket: gitlab-artifacts
      connection:
        secret: gitlab-object-storage
        key: connection
    uploads:
      bucket: gitlab-uploads
      connection:
        secret: gitlab-object-storage
        key: connection
    packages:
      enabled: false
    backups:
      bucket: gitlab-backup
      tmpBucket: gitlab-backup-tmp

registry:
  storage:
    secret: gitlab-registry-storage
    key: connection
