postgresql:
  install: false
gitlab-runner:
  install: false
prometheus:
  install: false
certmanager:
  install: false
nginx-ingress:
  enabled: false

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
  gitaly:
    persistence:
      size: 25Gi

minio:
  persistence:
    size: 10Gi

redis:
  master:
    persistence:
      size: 5Gi

registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1

global:
  edition: ce
  hosts:
    domain: k3s.samoth.eu
    https: false
    registry:
      name: gitlab-registry.k3s.samoth.eu
      https: false
    minio:
      name: gitlab-minio.k3s.samoth.eu
      https: false
    kas:
      name: gitlab-kas.k3s.samoth.eu
  ingress:
    configureCertmanager: false
    # Default, present here to be explicit.
    enabled: true
    # Toggle the TCP configuration and annotations to Traefik.
    provider: traefik
    # Alter the `kubernetes.io/ingress.class` annotation or
    # `spec.ingressClassName` value chart-wide.
    class: traefik
    annotations:
      # Tell Traefik that we've configured TLS
      # NOTE: disable this if `global.ingress.tls.enabled=false`.
      traefik.ingress.kubernetes.io/router.tls: "true"
      # Ensure the HTTP Routes only listen on 443, rather than all entrypoints.
      # NOTE: set the value to `web` if `global.ingress.tls.enabled=false`.
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
  # Tell the gitlab-shell chart which traefik entrypoint to use
  # Default, present here to be explicit. 
  gitlab-shell:
    traefik:
      entrypoint: "gitlab-shell"
  psql:
    host: gitlab-database.gitlab
    port: 5432
    database: gitlab
    username: gitlab
    password:
      useSecret: true
      secret: gitlab.gitlab-database.credentials.postgresql.acid.zalan.do
      key: password
