externalURL: https://harbor.k3s.samoth.eu
database:
  type: external
  external:
    host: harbor-database.harbor
    port: "5432"
    username: harbor
    coreDatabase: "registry"
    existingSecret: harbor.harbor-database.credentials.postgresql.acid.zalan.do
    sslmode: require
persistence:
  persistentVolumeClaim:
    registry:
      storageClass: "-"
    jobservice:
      jobLog:
        storageClass: sc-lvm
        size: 1Gi
    redis:
      storageClass: sc-lvm
      size: 1Gi
  imageChartStorage:
    type: s3
    s3:
      existingSecret: harbor-object-storage
      region: us-east-1
      bucket: harbor-registry
      regionendpoint: https://minio-api.k3s.samoth.eu
trivy:
  enabled: false