- name: install unattended-upgrades
  become: yes
  package:
    name: unattended-upgrades
    state: latest

- name: enable service
  systemd:
    state: started
    enabled: true
    name: unattended-upgrades

- name: copy unattended-upgrades config
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
  notify: reload unattended-upgrades