docker_user: "podboy"
config_folder: "/home/{{docker_user}}/docker"
dnscrypt_folder: "{{config_folder}}/dnscrypt"
dnscrypt_config: "{{dnscrypt_folder}}/dnscrypt-proxy.toml"
pihole_folder: "{{config_folder}}/pihole"
pihole_pihole_folder: "{{pihole_folder}}/pihole"
pihole_dnsmasqd_folder: "{{pihole_folder}}/dnsmasq.d"
pihole_password: "{{lookup('env', 'INFRA_PIHOLE_PASSWORD', default=Undefined)}}"
nebula_sync_webhook: "{{lookup('env', 'INFRA_NEBULA_SYNC', default=Undefined)}}"

ipv4_dns:
  - 1.1.1.1
  - 9.9.9.9
  - 8.8.8.8

ipv6_dns:
  - 2606:4700:4700::1111
  - 2620:fe::fe
  - 2001:4860:4860::8888