apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-postgres-operator-ui
  namespace: postgres-operator-ui
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`postgres-operator.k3s.samoth.eu`)
    kind: Rule
    services:
    - name: postgres-operator-ui
      port: 80