- import_tasks: firewall.yml

- name: setup qbittorrent container
  docker_container:
    name: "{{ qbt_container_name }}"
    image: linuxserver/qbittorrent
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ qbt_user | string }}"
      PGID: "{{ qbt_group | string }}"
      TZ: "{{ qbt_tz }}"
      WEBUI_PORT: "{{ qbt_internal_webui_port | string }}"
    volumes:
      - "{{ qbt_config_path }}:/config"
      - "{{ qbt_torrent_path }}:/downloads/ssd"
      - "{{ qbt_torrent_path_2 }}:/downloads/tank"
      - "{{ qbt_torrent_path_3 }}:/downloads/tank2"
    ports:
      - "{{ qbt_listening_port }}:{{ qbt_listening_port }}/tcp"
      - "{{ qbt_listening_port }}:{{ qbt_listening_port }}/udp"
      - "{{ qbt_internal_webui_port }}:{{ qbt_internal_webui_port }}/tcp"