- name: copy config
  copy:
    src: config.toml
    dest: /srv/gitlab-runner/config/config.toml
    owner: root
    group: root
    mode: "0600"

- name: install gitlab runner
  docker_container:
    name: gitlab_runner
    image: gitlab/gitlab-runner:latest
    restart_policy: unless-stopped
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner:Z
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      TZ: Europe/Paris
    state: started
    restart: true
