- name: base_ssh
  become: yes
  hosts: all:!proxmox
  roles:
    - ssh_hardening_prerequisites
    - devsec.hardening.ssh_hardening
  vars:
    ssh_allow_tcp_forwarding: yes
    ssh_allow_users: thomas
    ssh_client_password_login: "{{ not thomas_authorized_keys_file.stat.exists }}"