all:
  children:
    # distros
    rocky:
      hosts:
        LabDMZ:
          ansible_host: 192.168.0.36
        Frieren:
          ansible_host: 192.168.0.32
        PiHoleAlpha:
          ansible_host: 192.168.0.2
        PiHoleBeta:
          ansible_host: 192.168.0.3
      children:
        offsite1:
    debian:
      hosts:
        pbs2:
          ansible_ssh_user: root
          ansible_host: 192.168.0.33
      children:
        proxmox:
    proxmox:
      hosts:
        Akame:
          ansible_ssh_user: root
          ansible_host: 192.168.0.5
        Lynka:
          ansible_ssh_user: root
          ansible_host: 192.168.0.6
    raspbian:
      hosts:
  
    docker:
      hosts:
        PiHoleAlpha:
        PiHoleBeta:
        LabDMZ:
        Frieren:

    watchtower:
      children:
        docker:

    dns_server:
      hosts:
        PiHoleAlpha:
        PiHoleBeta:

    lan:
      children:
        proxmox:
        rocky: