all:
  children:
    # distros
    fedora:
      hosts:
        # maple
        192.168.0.18:
        qbt:
          ansible_host: 192.168.0.30
          ansible_port: 22002
        # fedora dmz
        192.168.4.10:
    rocky:
      hosts:
        LabProxy:
          ansible_host: 192.168.0.30
          ansible_port: 22000
        test:
          ansible_host: 192.168.70.148
      children:
        offsite1:
    debian:
      hosts:
        192.168.0.2:
        192.168.0.3:
        192.168.0.28:
      children:
        proxmox:
    proxmox:
      hosts:
        192.168.0.5:
          ansible_ssh_user: root
        192.168.0.6:
          ansible_ssh_user: root
    offsite1:
      hosts:
        vps.samoth.eu:
    raspbian:
      hosts:

    # apps
    torrent:
      hosts:
        qbt:
  
    docker:
      hosts:
        192.168.0.2:
        192.168.0.3:
        192.168.0.18:
        192.168.0.28:
        qbt:
        192.168.4.10:
        test:
        vps.samoth.eu:
        LabProxy:
        
    seafile_server:
      children:
        offsite1:

    qbittorrent:
      children:
        torrent:
        
    watchtower:
      children:
        docker:

    dns_server:
      hosts:
        192.168.0.2:
        192.168.0.3:
