all:
  children:
    # distros
    fedora:
      hosts:
        # maple
        192.168.0.18:
        # qbt
        192.168.2.10:
        # fedora dmz
        192.168.4.10:
        # fedora dmz 2
        192.168.4.11:
    rocky:
      hosts:
        # sentimail
        192.168.4.15:
        # K3sAkame
        192.168.5.2:
        # K3sLynka
        192.168.5.3:
        # GiteaRunnerAlpha
        192.168.5.4:
      children:
        offsite1:
    debian:
      hosts:
        192.168.0.2:
        192.168.0.3:
        192.168.0.28:
      children:
        proxmox:
    proxmox:
      hosts:
        192.168.0.4:
          ansible_ssh_user: root
        192.168.0.5:
          ansible_ssh_user: root
        192.168.0.6:
          ansible_ssh_user: root
    offsite1:
      hosts:
        vps.samoth.eu:
    raspbian:
      hosts:

    # apps
    torrent:
      hosts:
        192.168.2.10:
  
    docker:
      hosts:
        192.168.0.2:
        192.168.0.3:
        192.168.0.18:
        192.168.0.28:
        192.168.2.10:
        192.168.4.10:
        192.168.4.11:
        vps.samoth.eu:
        # GiteaRunnerAlpha
        192.168.5.4:
        
    seafile_server:
      children:
        offsite1:

    qbittorrent:
      children:
        torrent:
        
    watchtower:
      children:
        docker:

    dns_server:
      hosts:
        192.168.0.2:
        192.168.0.3:
    
    k3s:
      hosts:
        192.168.5.2:
        192.168.5.3:

    gitlab_runner:
      hosts:
        192.168.5.4: