all:
  children:
    # distros
    fedora:
      hosts:
        qbt:
          ansible_host: 192.168.0.35
    rocky:
      hosts:
        LabDMZ:
          ansible_host: 192.168.0.36
        Frieren:
          ansible_host: 192.168.0.32
        PiHoleAlpha:
          ansible_host: 192.168.0.2
        PiHoleBeta:
          ansible_host: 192.168.0.3
        PAR-630365:
          ansible_host: vps2.samoth.eu
      children:
        offsite1:
    debian:
      hosts:
        pbs:
          ansible_ssh_user: root
          ansible_host: 192.168.0.33
      children:
        proxmox:
    proxmox:
      hosts:
        Akame:
          ansible_ssh_user: root
          ansible_host: 192.168.0.5
        Lynka:
          ansible_ssh_user: root
          ansible_host: 192.168.0.6
    raspbian:
      hosts:

    # apps
    torrent:
      hosts:
        qbt:
  
    docker:
      hosts:
        PiHoleAlpha:
        PiHoleBeta:
        qbt:
        LabDMZ:
        Frieren:
        PAR-630365:

    qbittorrent:
      children:
        torrent:
        
    watchtower:
      children:
        docker:

    dns_server:
      hosts:
        PiHoleAlpha:
        PiHoleBeta:

    lan:
      children:
        proxmox:
        rocky:
        fedora: