all:
  children:
    # distros
    fedora:
      hosts:
        # maple
        192.168.0.18:
        # ?
        192.168.0.27:
        # qbt
        192.168.2.10:
        # fedora dmz
        192.168.4.10:
        192.168.4.20:
    rocky:
      hosts:
        # pihole
        192.168.0.3:
        # sentimail
        192.168.4.15:
        # ???
        192.168.0.31:
      children:
        offsite1:
    ubuntu:
      hosts:
        192.168.0.2:
    debian:
      hosts:
        # obelix
        192.168.0.28:
      children:
        proxmox:
    proxmox:
      hosts:
        192.168.0.4:
          ansible_ssh_user: root
        192.168.0.5:
          ansible_ssh_user: root
        192.168.0.6:
          ansible_ssh_user: root
    offsite1:
      hosts:
        vps.samoth.eu:
    raspbian:
      hosts:

    # apps
    torrent:
      hosts:
        192.168.2.10:
  
    docker:
      hosts:
        192.168.0.2:
        192.168.0.18:
        192.168.0.28:
        192.168.2.10:
        192.168.4.10:
        vps.samoth.eu:
    
    k8s:
      hosts:
        192.168.0.31:
        
    seafile_server:
      children:
        offsite1:

    qbittorrent:
      children:
        torrent:
        
    watchtower:
      children:
        docker:
