all:
  children:
    # distros
    fedora:
      hosts:
        # maple
        192.168.0.18:
        qbt:
          ansible_host: 192.168.0.30
          ansible_port: 22002
        # fedora dmz
        192.168.4.10:
    rocky:
      hosts:
        LabProxy:
          ansible_host: 192.168.0.30
          ansible_port: 22000
        LabSyrup:
          ansible_host: 192.168.0.30
          ansible_port: 22003
        LabOboro:
          ansible_host: 192.168.0.30
          ansible_port: 22004
        test:
          ansible_host: 192.168.70.148
      children:
        offsite1:
    debian:
      hosts:
        PiHoleAlpha:
        PiHoleBeta:
        192.168.0.28:
      children:
        proxmox:
    proxmox:
      hosts:
        192.168.0.5:
          ansible_ssh_user: root
        192.168.0.6:
          ansible_ssh_user: root
    offsite1:
      hosts:
        vps.samoth.eu:
    raspbian:
      hosts:

    # network zone
    real_lan:
      hosts:
        PiHoleAlpha:
          ansible_host: 192.168.0.2
        PiHoleBeta:
          ansible_host: 192.168.0.3
        192.168.0.18:
        192.168.0.28:

    Lab:
      children:
        LabLAN:
        LabDMZ:
        LabVYOS:

    LabLAN:
      hosts:
        LabSyrup:
        LabOboro:
    
    LabDMZ:
      hosts:
        LabProxy:

    # apps
    torrent:
      hosts:
        qbt:
  
    docker:
      hosts:
        PiHoleAlpha:
        PiHoleBeta:
        192.168.0.18:
        192.168.0.28:
        qbt:
        192.168.4.10:
        test:
        vps.samoth.eu:
        LabProxy:
        LabSyrup:
        LabOboro:
        
    seafile_server:
      children:
        offsite1:

    qbittorrent:
      children:
        torrent:
        
    watchtower:
      children:
        docker:

    dns_server:
      hosts:
        PiHoleAlpha:
        PiHoleBeta:

    k3s:
      hosts:
        LabOboro: