all:
  children:
    # distros
    fedora:
      hosts:
        192.168.0.18:
        192.168.0.27:
        192.168.2.10:
        192.168.4.10:
    rocky:
      hosts:
        192.168.0.3:
        192.168.4.15:
    ubuntu:
      hosts:
        192.168.0.2:
      children:
        offsite1:
    debian:
      hosts:
        192.168.0.94:
      children:
        proxmox:
    proxmox:
      hosts:
        192.168.0.4:
          ansible_ssh_user: root
        192.168.0.5:
          ansible_ssh_user: root
        192.168.0.6:
          ansible_ssh_user: root
    offsite1:
      hosts:
        vps.samoth.eu:
    raspbian:
      hosts:

    # apps
    torrent:
      hosts:
        192.168.2.10:
  
    docker:
      hosts:
        192.168.0.2:
        192.168.0.18:
        192.168.0.28:
        192.168.2.10:
        192.168.4.10:
        vps.samoth.eu:
    podman:
      hosts:
        192.168.0.3:
        192.168.70.138:
        
    seafile_server:
      children:
        offsite1:

    qbittorrent:
      children:
        torrent:
        
    watchtower:
      children:
        docker:
