all:
  children:
    # distros
    fedora:
      hosts:
        qbt:
          ansible_host: 192.168.0.30
          ansible_port: 22002
    rocky:
      hosts:
        LabProxy:
          ansible_host: 192.168.0.30
          ansible_port: 22000
        LabSyrup:
          ansible_host: 192.168.0.30
          ansible_port: 22003
        LabOboro:
          ansible_host: 192.168.0.30
          ansible_port: 22004
        LabDMZ:
          ansible_host: 192.168.0.30
          ansible_port: 22005
        Frieren:
          ansible_host: 192.168.0.32
        PiHoleAlpha:
          ansible_host: 192.168.0.2
        PiHoleBeta:
          ansible_host: 192.168.0.3
        PAR-630365:
          ansible_host: vps2.samoth.eu
      children:
        offsite1:
    debian:
      hosts:
        pbs:
          ansible_ssh_user: root
          ansible_host: 192.168.0.29
      children:
        proxmox:
    proxmox:
      hosts:
        Akame:
          ansible_ssh_user: root
          ansible_host: 192.168.0.5
        Lynka:
          ansible_ssh_user: root
          ansible_host: 192.168.0.6
    offsite1:
      hosts:
        vps.samoth.eu:
    raspbian:
      hosts:

    # network zone
    RealLan:
      hosts:
        PiHoleAlpha:
        PiHoleBeta:
        Frieren:
      children:
        Labo:

    Labo:
      children:
        LaboLAN:
        LaboPROXY:
        LaboVYOS:
        LaboDMZ:

    LaboLAN:
      hosts:
        LabSyrup:
        LabOboro:
    
    LaboPROXY:
      hosts:
        LabProxy:

    LaboDMZ:
      hosts:
        LabDMZ:

    # apps
    torrent:
      hosts:
        qbt:
  
    docker:
      hosts:
        PiHoleAlpha:
        PiHoleBeta:
        qbt:
        vps.samoth.eu:
        LabProxy:
        LabSyrup:
        LabOboro:
        LabDMZ:
        Frieren:
        PAR-630365:

    qbittorrent:
      children:
        torrent:
        
    watchtower:
      children:
        docker:

    dns_server:
      hosts:
        PiHoleAlpha:
        PiHoleBeta:

    k3s:
      hosts:
        LabOboro: