apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    globalArguments:
    - "--global.checknewversion"
    logs:
      general:
        level: INFO
    forwardedHeaders:
      enabled: true
      trustedIPs:
        - 10.0.0.0/8
    ports:
      web:
        expose: false
      websecure:
        tls:
          enabled: true
          certResolver: letsencrypt
          domains:
            - main: "k3s.samoth.eu"
              sans:
                - "*.k3s.samoth.eu"
    tlsOptions:
      default:
        minVersion: VersionTLS13
    env:
    - name: CF_DNS_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-secret
          key: token
    persistence:
      enabled: true
    certResolvers:
      letsencrypt:
        email: thomasviolent@gmail.com
        storage: /data/acme.json
        dnsChallenge:
          provider: cloudflare
          delayBeforeCheck: 10
          resolvers:
            - 1.1.1.1
            - 1.0.0.1
    deployment:
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
          volumeMounts:
          - mountPath: /data
            name: data
