# https://doc.traefik.io/traefik/middlewares/http/ratelimit/#period
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: middleware-internet-ratelimit
  namespace: kube-system
spec:
  rateLimit:
    average: 25
    burst: 50
    period: 5
