apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5sYWIuc2Ftb3RoLmV1IjogewoJCQkiYXV0aCI6ICJjbVZoWkdWeU9qRXlNeXRoZW1VPSIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
