apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-lvm
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
provisioner: local.csi.openebs.io
parameters:
  storage: "lvm"
  volgroup: "m2vg"
  shared: "yes"             ## Parameter that states volume can be shared among multiple pods
  thinProvision: "yes"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowedTopologies:
  - matchLabelExpressions:
    - key: openebs.io/nodename
      values:
        - k3sakame