- name: install dnf-plugins-core
  package:
    name: dnf-plugins-core
    state: latest

# c'est un peu sale comme méthode, mais il y a ~10 repo à mettre en place avec leurs clés gpg
- name: adding docker repo
  command: sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  become: true

- name: install docker-ce
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - fuse-overlayfs
      - iptables
      - docker-ce-rootless-extras
    state: latest

- name: disable system (root) docker
  systemd:
    state: stopped
    enabled: no
    name: docker

- name: create user {{ docker_user }}
  user:
    name: "{{ docker_user }}"
    state: present
    password_lock: true

- name: start docker with {{ docker_user }}
  become: true
  become_user: "{{ docker_user }}"
  systemd:
    state: started
    enabled: yes
    scope: user
    name: docker