- name: install docker engine for RHEL distros
  block:
    - name: copy repo file
      copy:
        src: docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        owner: root
        group: root
        mode: 0644
    - name: install docker engine
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
  when: ansible_distribution == 'Rocky'

- name: get installed packages
  package_facts:
    manager: auto

- name: fail if docker isn't installed
  fail:
    msg: Docker engine need to be installed
  when: "'docker-ce' not in ansible_facts.packages"

- name: create user podboy
  user:
    name: podboy
    expires: -1
    password_lock: yes
    password: "!"
    shell: /bin/bash

- name: create podboy docker folder
  file:
    path: /home/podboy/docker
    group: podboy
    owner: podboy
    mode: u=rwx
    state: directory

- name: check if docker is started and enabled at boot
  systemd:
    name: "{{item}}"
    state: started
    enabled: true
  with_items:
    - docker.service
    - containerd.service

- name: logging driver config docker
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0444
  notify: restart docker

- name: adding pip and potentially needed packages
  package:
    name:
      - python3
      - python3-pip

- name: adding requests
  pip:
    name:
      # TODO fix this when this is fixed https://github.com/docker/docker-py/issues/3113
      - requests<2.2.29
    state: present